### ISSUE TITLE
'Failed to obtain root' error on Windows

### ISSUE THREAD

**Issue by xiety** [madyankin/postcss-modules#140]
Sometimes `process.cwd()` returns path with a small drive letter, like `d:\`

And this regex `!/^[A-Z]:\\$/.test(cwdDrive)` is failed to match it.

Possible solution is to use this regex `!/^[A-Za-z]:\\$/.test(cwdDrive)`

https://github.com/madyankin/postcss-modules/blob/55b09950d76140ddef25fd60f4fd788b773f8e70/src/css-loader-core/loader.js#L49

**Comment by meixger** [comment]
ref: VSCode normalizes the drive letter case: https://github.com/microsoft/vscode/blob/main/src/vs/platform/terminal/common/terminalEnvironment.ts#L51
