### ISSUE TITLE
doesn't work with :is and :where clauses

### ISSUE THREAD

**Issue by lucax88x** [madyankin/postcss-modules#152]
I did some comparison with css-loader because this one works.

css-loader with modules = true, postcss with modules = false

```
:is(.text_page-title__2n9GB, .text_headline-regular__2eBkX, .text_headline-small__y3WMM) {
}
 
.text_page-title__2n9GB {
}
```

Correctly prefix & hashes both cases.

css-loader with modules = false & postcss with modules = false

```
is(.page-title, .headline-regular, .headline-small) {
}
 
.page-title {
}
```

Correctly does nothing.

css-loader with modules = false & postcss with modules = true

```
:is(.page-title, .headline, .headline-small) {
}
 
.text_vp__text-module__page-title___2cZqa__1MYR9 {
}
```

Wrong, postcss is bugged, handles only the one without pseudo class

css-loader with modules = true & postcss with modules = true

```
:is(.text_page-title__2n9GB, .text_headline-regular__2eBkX, .text_headline-small__y3WMM) {
}
 
.text_vp__text-module__page-title___2cZqa__1MYR9 {
}
```

Wrong, The css-loader handles both, but poscss works only on the second one, in-fact you see the double prefix & and double hash in the second one

Another proof, postcss without rollup or CRA

npx postcss-cli --config ./postcss.module.config.js src/modules/ui/typography/text.module.scss

produces

```
:is(.page-title, .headline, .headline-small) {
}
 
.text_vp__text-module__page-title___2cZqa__1MYR9 {
}
```

**Comment by madyankin** [comment]
Thanks for the report. I have moved to another country a couple of months ago, so I'm solving different related quests right now and not able to take a look into it. So, PR is welcome if you want this to be fixed.
